spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybank_dev
    username: postgres
    password: password
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      
logging:
  level:
    com.mybank: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
management:
  endpoints:
    web:
      exposure:
        include: "*" 