steps:
  # Build the application
  - name: 'gradle:8.4-jdk21'
    entrypoint: gradle
    args: ['build', '--no-daemon']
    dir: '.'

  # Copy the JAR to the root directory for Docker
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -la build/libs/
        cp build/libs/workspace-0.1.0.jar app.jar
        echo "JAR copied successfully"
        ls -la app.jar

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mybank-api:latest', '-f', 'deployment/Dockerfile', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mybank-api:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mybank-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mybank-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'

images:
  - 'gcr.io/$PROJECT_ID/mybank-api:latest' 